### ISSUE TITLE
Mod crashes when using it in a server.

### ISSUE THREAD

**Issue by zDany01** [HugoMage/MonkeMadnessRemake#2]
I'm unable to use this mod in my modded server.
Here is some information about my setup:
Mod Loaded: Only MonkeMadness
Minecraft Forge: v39.0.63
Server error:
```
Failed to create mod instance. ModID: monke_madness, class com.hugomage.primate.Primate
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderLayerParent
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.63.jar%2341!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.63.jar%2340!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.RenderLayerParent
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
```

I hope that this can get fixed.
If it helps these are the server logs:
[latest.log](https://github.com/HugoMage/MonkeMadnessRemake/files/7963784/latest.log)
[crash-2022-01-29_14.36.17-fml.txt](https://github.com/HugoMage/MonkeMadnessRemake/files/7963785/crash-2022-01-29_14.36.17-fml.txt)

**Comment by HugoMage** [comment]
Can you tell me what version of monke madness you might be playing

**Comment by zDany01** [comment]
Oh, sorry for the inconvenience.
I realized that I am not running the latest version of the mod, I don't understand why curseforge has not downloaded the latest version of the mod from the main page.
From the files section I downloaded and tried the latest version of the mod and it works fine.
Sorry my bad, I should have checked before opening an issue
